version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: familyhub-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: familyhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: familyhub-backend
    restart: unless-stopped
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@db:5432/familyhub
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Frontend (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: familyhub-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3001/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
